import type { Question } from "./types";

export const curatedQuestions: Question[] = [
  {id:"of-01",prompt:"A lens has a focal length of +0.50 m in air. What is its approximate power?",options:["+0.50 D","+2.00 D","−0.50 D","−2.00 D"],correctIndex:1,rationale:"Lens power in diopters is the reciprocal of focal length in meters: 1 ÷ 0.50 = +2.00 D.",topic:"Optics fundamentals",difficulty:"foundation",source:"curated"},
  {id:"of-02",prompt:"Which description best fits a minus-powered spherical lens?",options:["Thicker at the center than the edge","Equal thickness throughout","Thinner at the center than the edge","Flat on both surfaces"],correctIndex:2,rationale:"A minus lens is characteristically thinner centrally and thicker toward the edge.",topic:"Optics fundamentals",difficulty:"foundation",source:"curated"},
  {id:"of-03",prompt:"When light passes from air into a typical spectacle lens at an angle, it generally bends:",options:["Away from the normal","Toward the normal","Parallel to the surface","Back toward the source"],correctIndex:1,rationale:"Light entering a denser optical medium slows and refracts toward the normal.",topic:"Optics fundamentals",difficulty:"foundation",source:"curated"},
  {id:"of-04",prompt:"Two thin lenses of +2.00 D and −0.75 D are placed in contact. What is their combined power?",options:["+2.75 D","+1.25 D","−1.25 D","−2.75 D"],correctIndex:1,rationale:"Thin lens powers in contact add algebraically: +2.00 + (−0.75) = +1.25 D.",topic:"Optics fundamentals",difficulty:"applied",source:"curated"},
  {id:"of-05",prompt:"A ray passing through the optical center of a thin lens is commonly treated as:",options:["Undeviated","Totally reflected","Split into colors only","Parallel to the optical axis"],correctIndex:0,rationale:"In the thin-lens approximation, a ray through the optical center continues without meaningful deviation.",topic:"Optics fundamentals",difficulty:"foundation",source:"curated"},
  {id:"of-06",prompt:"Using Prentice’s rule, what prism is induced 5 mm from the optical center of a +4.00 D lens?",options:["0.20 prism diopter","1.25 prism diopters","2.00 prism diopters","20.00 prism diopters"],correctIndex:2,rationale:"P = cF, with c in centimeters: 0.5 × 4.00 = 2.00 prism diopters.",topic:"Optics fundamentals",difficulty:"challenge",source:"curated"},
  {id:"of-07",prompt:"The wavelength range ordinarily perceived by the human eye is referred to as:",options:["Ultraviolet radiation","Visible light","Infrared radiation","X-radiation"],correctIndex:1,rationale:"Visible light is the portion of the electromagnetic spectrum detected by the human visual system.",topic:"Optics fundamentals",difficulty:"foundation",source:"curated"},

  {id:"ol-01",prompt:"Which lens material property most directly describes resistance to scratching?",options:["Abbe value","Surface hardness","Specific gravity","Refractive index"],correctIndex:1,rationale:"Surface hardness relates to scratch resistance; coatings may further improve it.",topic:"Ophthalmic lenses",difficulty:"foundation",source:"curated"},
  {id:"ol-02",prompt:"A lower Abbe value is generally associated with:",options:["Less chromatic dispersion","More chromatic dispersion","Higher impact resistance only","Lower lens power"],correctIndex:1,rationale:"Lower Abbe values indicate greater chromatic dispersion, which may produce more color fringing.",topic:"Ophthalmic lenses",difficulty:"applied",source:"curated"},
  {id:"ol-03",prompt:"The primary purpose of an anti-reflective coating is to:",options:["Increase surface reflections","Reduce reflected light","Change lens power","Guarantee scratch immunity"],correctIndex:1,rationale:"Anti-reflective treatment reduces surface reflections and can improve light transmission and appearance.",topic:"Ophthalmic lenses",difficulty:"foundation",source:"curated"},
  {id:"ol-04",prompt:"In a conventional lined bifocal, the segment provides:",options:["Distance correction only","Near addition power","Cylinder cancellation","Automatic photochromic activation"],correctIndex:1,rationale:"The segment adds plus power relative to the distance portion for near viewing.",topic:"Ophthalmic lenses",difficulty:"foundation",source:"curated"},
  {id:"ol-05",prompt:"Which prescription component specifies astigmatic power?",options:["Sphere only","Cylinder","Add only","Prism base only"],correctIndex:1,rationale:"Cylinder power, together with its axis, specifies the astigmatic component.",topic:"Ophthalmic lenses",difficulty:"foundation",source:"curated"},
  {id:"ol-06",prompt:"Transposing −2.00 +1.00 × 090 into minus-cylinder form gives:",options:["−1.00 −1.00 × 180","−3.00 −1.00 × 180","−1.00 −1.00 × 090","−2.00 −1.00 × 180"],correctIndex:0,rationale:"Add sphere and cylinder (−1.00), reverse cylinder sign (−1.00), and rotate axis 90° (180).",topic:"Ophthalmic lenses",difficulty:"challenge",source:"curated"},
  {id:"ol-07",prompt:"Photochromic lenses are designed primarily to change transmission in response to:",options:["Sound","Ultraviolet exposure","Frame pressure","Near fixation"],correctIndex:1,rationale:"Photochromic molecules darken with activating radiation, chiefly UV, and fade as exposure falls.",topic:"Ophthalmic lenses",difficulty:"applied",source:"curated"},

  {id:"fm-01",prompt:"Monocular pupillary distances are especially useful because they account for:",options:["Unequal right and left centration distances","Lens tint density","Temple length","Bridge material"],correctIndex:0,rationale:"Monocular PDs locate each pupil relative to the facial midline and capture asymmetry.",topic:"Frame fitting & measurements",difficulty:"applied",source:"curated"},
  {id:"fm-02",prompt:"In boxing measurements, the “A” dimension is the:",options:["Vertical lens size","Horizontal lens size","Distance between lenses","Overall temple length"],correctIndex:1,rationale:"The A dimension is the horizontal width of the lens shape’s boxing rectangle.",topic:"Frame fitting & measurements",difficulty:"foundation",source:"curated"},
  {id:"fm-03",prompt:"The distance between lenses (DBL) is measured between the:",options:["Pupil centers","Closest points of the two lens shapes","Temple tips","Geometric centers vertically"],correctIndex:1,rationale:"DBL is the minimum horizontal distance between the boxed lens shapes.",topic:"Frame fitting & measurements",difficulty:"foundation",source:"curated"},
  {id:"fm-04",prompt:"Frame PD (geometric center distance) is calculated as:",options:["A + DBL","B + DBL","A − DBL","ED + B"],correctIndex:0,rationale:"Frame PD equals one lens shape’s A dimension plus the distance between lenses.",topic:"Frame fitting & measurements",difficulty:"applied",source:"curated"},
  {id:"fm-05",prompt:"Pantoscopic tilt describes the angle formed when the:",options:["Lower eyewire is closer to the cheeks than the upper eyewire","Upper eyewire is closer to the cheeks than the lower eyewire","Frame front rotates horizontally","Temples spread at the hinges"],correctIndex:0,rationale:"Pantoscopic tilt places the lower portion of the frame front closer to the face.",topic:"Frame fitting & measurements",difficulty:"foundation",source:"curated"},
  {id:"fm-06",prompt:"A frame has A = 52 mm and DBL = 18 mm. Its frame PD is:",options:["34 mm","52 mm","70 mm","88 mm"],correctIndex:2,rationale:"Frame PD = A + DBL = 52 + 18 = 70 mm.",topic:"Frame fitting & measurements",difficulty:"applied",source:"curated"},
  {id:"fm-07",prompt:"Effective diameter is most useful when estimating:",options:["Minimum lens blank size","Near addition","Temple bend angle","Lens transmission"],correctIndex:0,rationale:"Effective diameter helps determine the minimum blank diameter needed to cut a lens shape.",topic:"Frame fitting & measurements",difficulty:"challenge",source:"curated"},

  {id:"di-01",prompt:"Before taking fitting measurements for a new frame, the dispenser should first:",options:["Heat both temples","Perform a preliminary frame adjustment","Remove the nose pads","Mark the demo lenses at random"],correctIndex:1,rationale:"The frame should sit properly on the wearer before measurements are recorded.",topic:"Dispensing",difficulty:"foundation",source:"curated"},
  {id:"di-02",prompt:"When verifying a finished pair, the lensometer is primarily used to check:",options:["Frame color","Lens optical power","Temple material","Patient acuity"],correctIndex:1,rationale:"A lensometer measures or verifies lens power, axis, add, and prism as applicable.",topic:"Dispensing",difficulty:"foundation",source:"curated"},
  {id:"di-03",prompt:"A wearer reports that the frame slides down repeatedly. A useful first assessment is the:",options:["Bridge and temple fit","Prescription axis only","Lens Abbe value only","Case size"],correctIndex:0,rationale:"Bridge contact, temple alignment, and temple bend commonly affect frame stability.",topic:"Dispensing",difficulty:"applied",source:"curated"},
  {id:"di-04",prompt:"Why should a dispenser inspect eyewear before handing it to the wearer?",options:["To replace verification procedures","To identify cosmetic, assembly, and cleanliness issues","To change the prescription","To avoid making any adjustments"],correctIndex:1,rationale:"A final inspection catches visible defects, loose hardware, poor assembly, and cleanliness concerns.",topic:"Dispensing",difficulty:"foundation",source:"curated"},
  {id:"di-05",prompt:"For a progressive addition lens, fitting height is commonly referenced from the:",options:["Lowest point of the eyewire only","Fitting cross to the appropriate frame datum","Temple tip to the hinge","Bridge center to lens edge"],correctIndex:1,rationale:"PAL fitting uses the manufacturer’s fitting cross positioned relative to the pupil and measured to the specified frame reference.",topic:"Dispensing",difficulty:"challenge",source:"curated"},
  {id:"di-06",prompt:"If a patient has persistent visual discomfort after delivery, the best next step is to:",options:["Dismiss the concern immediately","Systematically recheck prescription, measurements, frame fit, and use","Increase both lens powers","Advise permanent non-wear"],correctIndex:1,rationale:"A structured troubleshooting sequence identifies prescription, fabrication, fit, or adaptation factors.",topic:"Dispensing",difficulty:"applied",source:"curated"},

  {id:"sr-01",prompt:"Which lens material is commonly selected when impact resistance is a major priority?",options:["Standard crown glass","Polycarbonate","Uncoated high-index glass","Flint glass"],correctIndex:1,rationale:"Polycarbonate is widely used for its high impact resistance, though product selection must follow applicable requirements.",topic:"Safety & regulatory basics",difficulty:"foundation",source:"curated"},
  {id:"sr-02",prompt:"The safest response to an unfamiliar chemical splashed in the eye is to:",options:["Neutralize it with another chemical","Follow emergency flushing guidance and seek appropriate medical help","Wait for vision to blur","Rub the eye firmly"],correctIndex:1,rationale:"Immediate irrigation and appropriate emergency or medical guidance are safer than attempting chemical neutralization.",topic:"Safety & regulatory basics",difficulty:"foundation",source:"curated"},
  {id:"sr-03",prompt:"Why should an optical practice document final inspection findings?",options:["To create a traceable quality record","To guarantee a medical outcome","To replace staff training","To avoid following local rules"],correctIndex:0,rationale:"Documentation supports quality control and traceability; exact obligations depend on jurisdiction and setting.",topic:"Safety & regulatory basics",difficulty:"applied",source:"curated"},
  {id:"sr-04",prompt:"When dispensing protective eyewear for a workplace, the optician should prioritize:",options:["Fashion preference over all else","Applicable hazard assessment and current standards","The thinnest lens regardless of use","A verbal promise of indestructibility"],correctIndex:1,rationale:"Protective eyewear selection should match the identified hazard and applicable current safety standards.",topic:"Safety & regulatory basics",difficulty:"applied",source:"curated"},
  {id:"sr-05",prompt:"Which claim about safety eyewear is responsible?",options:["All spectacles provide identical protection","Safety markings and requirements should be verified for the intended use","Any tinted lens is certified protection","A strong frame makes standards irrelevant"],correctIndex:1,rationale:"Certification, markings, and use-specific requirements matter; ordinary eyewear is not automatically protective eyewear.",topic:"Safety & regulatory basics",difficulty:"foundation",source:"curated"},
  {id:"sr-06",prompt:"If local dispensing rules conflict with a study summary, which source should govern practice?",options:["The study summary","Current law, regulation, and professional guidance in that jurisdiction","An old product brochure","A social media post"],correctIndex:1,rationale:"Legal and professional requirements vary and change; current authoritative local guidance governs practice.",topic:"Safety & regulatory basics",difficulty:"foundation",source:"curated"}
];
